#pragma once

#define _PRINT_ESC(s) printf(CONSOLE_ESC(s))
#define _EXPAND(a) a

#define CONSOLE_ATTR_NONE 0
#define CONSOLE_ATTR_BOLD 1
#define CONSOLE_ATTR_LIGHT 2
#define CONSOLE_ATTR_UNDERSCORE 4
#define CONSOLE_ATTR_BLINK 5
#define CONSOLE_ATTR_REVERSE 7
#define CONSOLE_ATTR_CONCEALED 8
#define CONSOLE_ATTR_STRIKETHROUGH 9

#define CONSOLE_COLOR_BLACK 30
#define CONSOLE_COLOR_RED 31
#define CONSOLE_COLOR_GREEN 32
#define CONSOLE_COLOR_YELLOW 33
#define CONSOLE_COLOR_BLUE 34
#define CONSOLE_COLOR_MAGENTA 35
#define CONSOLE_COLOR_CYAN 36
#define CONSOLE_COLOR_WHITE 37

#define CONSOLE_SET_ATTRS(a) _PRINT_ESC(_EXPAND(a)m)

#define CONSOLE_SET_COLOR(color) CONSOLE_SET_ATTRS(color)

#define CONSOLE_CLEAR_SCREEN() _PRINT_ESC(2J)
#define CONSOLE_CLEAR_LINE() _PRINT_ESC(K)

#define CONSOLE_SET_POS(x, y) _PRINT_ESC(_EXPAND(x);_EXPAND(y)H)
#define CONSOLE_MOVE_UP(lines) _PRINT_ESC(_EXPAND(lines)A)
#define CONSOLE_MOVE_DOWN(lines) _PRINT_ESC(_EXPAND(lines)B)
#define CONSOLE_MOVE_RIGHT(cols) _PRINT_ESC(_EXPAND(cols)C)
#define CONSOLE_MOVE_LEFT(cols) _PRINT_ESC(_EXPAND(cols)D)

#define CONSOLE_PUSH_POS() _PRINT_ESC(s)
#define CONSOLE_POP_POS() _PRINT_ESC(u)
